#!/bin/bash


start_script() {
	[ -x openvpn ] || systemctl stop openvpn
	[ -x transmission-daemon ] || systemctl stop transmission-daemon
	killall openvpn >> /dev/null 2>&1
	sleep 2
	killall -9 openvpn >> /dev/null 2>&1

	CLIENT=`ls /etc/openvpn/client | shuf -n 1`
	openvpn --config /etc/openvpn/client/$CLIENT >> /dev/null 2>&1 &
	sleep 20
	systemctl start transmission-daemon
	CHECKTUN=`ip -o -f inet addr show | awk '/scope global/' | grep tun0 | awk '{print $2}'`

	while [[ $CHECKTUN = tun0 ]]; do
		sleep 10
		CHECKTUN=`ip -o -f inet addr show | awk '/scope global/' | grep tun0 | awk '{print $2}'`
		sleep 10
	done

	systemctl stop transmission-daemon
}

stop_script() {
	[ -x openvpn ] || systemctl stop openvpn
	[ -x transmission-daemon ] || systemctl stop transmission-daemon
	killall openvpn >> /dev/null 2>&1
	sleep 2
	killall -9 openvpn >> /dev/null 2>&1
}

status() {
	clear
	PRESS="             ***** Press ENTER to continue *****"
	EXTIP=$(curl -s icanhazip.com)
	COUNTRY=$(whois $EXTIP | grep -m 1 country: | awk '{print $2}')
	CHECKTUN=`ip -o -f inet addr show | awk '/scope global/' | grep tun0 | awk '{print $2}'`
	if [[ $CHECKTUN = tun0 ]]; then
		echo && echo -e '\e[32m'"You are connected with OpenVPN: your IP is $EXTIP $COUNTRY"
		echo "$PRESS" && echo -e '\e[0m'
	else
		echo && echo -e '\e[91m'"You are NOT connected with OpenVPN: your IP is $EXTIP $COUNTRY"
		[ -x transmission-daemon ] || systemctl stop transmission-daemon
		echo "$PRESS" && echo -e '\e[0m'
	fi
}

help_script() {
	echo
	echo
	echo
}


case "$1" in
start)
	start_script &
	;;
stop)
	stop_script
	;;
restart)
	start_script &
	;;
status)
	status &
	;;
help)
	help_script
	;;
*)
	echo "Usage: $0 {start|stop|restart|status|help}"
esac

exit 0
